kind: Service
apiVersion: v1
metadata:
  name: xy-pay
spec:
  selector:
    app: xy-pay
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xy-pay-guangzhou
  labels:
    app: xy-pay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xy-pay
  template:
    metadata:
      labels:
        app: xy-pay
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      nodeSelector:
        union: guangzhou
      containers:
      - name: demo
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 600Mi
        volumeMounts:
          - name: varlog
            mountPath: /var/log
      - name: fluent-sidecar
        image: registry.cn-beijing.aliyuncs.com/k8s-mqm/fluentd-elasticsearch:v2.1.0
        resources:
          limits:
            cpu: 75m
            memory: 100Mi
          requests:
            cpu: 75m
            memory: 100Mi
        env:
          - name: FLUENTD_ARGS
            value: -c /etc/fluentd-config/fluentd.conf
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: config-volume
            mountPath: /etc/fluentd-config
      volumes:
        - name: varlog
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xy-pay-shanghai
  labels:
    app: xy-pay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xy-pay
  template:
    metadata:
      labels:
        app: xy-pay
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeSelector:
          union: shanghai
      containers:
        - name: demo
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
        - name: fluent-sidecar
          image: registry.cn-beijing.aliyuncs.com/k8s-mqm/fluentd-elasticsearch:v2.1.0
          resources:
            limits:
              cpu: 70m
              memory: 75Mi
            requests:
              cpu: 70m
              memory: 75Mi
          env:
            - name: FLUENTD_ARGS
              value: -c /etc/fluentd-config/fluentd.conf
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config-volume
              mountPath: /etc/fluentd-config
      volumes:
        - name: varlog
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-config
