kind: Service
apiVersion: v1
metadata:
  name: xy-pay
spec:
  selector:
    app: xy-pay
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xy-pay-guangzhou
  labels:
    app: xy-pay
spec:
  #副本个数
  replicas: 2
  selector:
    matchLabels:
      app: xy-pay
  template:
    metadata:
      labels:
        app: xy-pay
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      #选择广州的机器发布
      nodeSelector:
        union: guangzhou
      containers:
      - name: demo
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        #容器开放的port
        ports:
        - containerPort: 8080
        #资源地址
        resources:
          limits:
            cpu: 200m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 600Mi
        #设置探活指针
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
              - name: Host
                value: 127.0.0.1
            path: /version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
              - name: Host
                value: 127.0.0.1
            path: /version
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 2
          timeoutSeconds: 2
        #挂载磁盘
        volumeMounts:
          - name: varlog
            mountPath: /var/log
      #sidecar 上传日志
      - name: fluent-sidecar
        image: registry.cn-beijing.aliyuncs.com/k8s-mqm/fluentd-elasticsearch:v2.1.0
        resources:
          limits:
            cpu: 75m
            memory: 100Mi
          requests:
            cpu: 75m
            memory: 100Mi
        env:
          - name: FLUENTD_ARGS
            value: -c /etc/fluentd-config/fluentd.conf
        volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: config-volume
            mountPath: /etc/fluentd-config
      volumes:
        - name: varlog
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xy-pay-shanghai
  labels:
    app: xy-pay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xy-pay
  template:
    metadata:
      labels:
        app: xy-pay
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      nodeSelector:
          union: shanghai
      containers:
        - name: demo
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 600Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
              path: /version
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Host
                  value: 127.0.0.1
              path: /version
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 2
            timeoutSeconds: 2
        - name: fluent-sidecar
          image: registry.cn-beijing.aliyuncs.com/k8s-mqm/fluentd-elasticsearch:v2.1.0
          resources:
            limits:
              cpu: 70m
              memory: 75Mi
            requests:
              cpu: 70m
              memory: 75Mi
          env:
            - name: FLUENTD_ARGS
              value: -c /etc/fluentd-config/fluentd.conf
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config-volume
              mountPath: /etc/fluentd-config
      volumes:
        - name: varlog
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-config
